[package]
name = "sysy-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
koopa = "0.0.9"
lalrpop-util = { version = "0.22.2", features = ["lexer"] }

[build-dependencies]
lalrpop = "0.22.2"
